---
deployment:
  tasks:
    # Deploy Laravel app to home directory (outside public_html)
    - export APPPATH=/home/txepiedg/finora_app
    - export PUBLICPATH=/home/txepiedg/public_html
    
    # Create app directory if not exists
    - /bin/mkdir -p $APPPATH
    
    # Copy all Laravel files to app directory
    - /bin/cp -R . $APPPATH/
    
    # Remove old public_html contents (except cPanel files)
    - /bin/rm -rf $PUBLICPATH/* 2>/dev/null || true
    
    # Copy public folder contents to public_html
    - /bin/cp -R $APPPATH/public/* $PUBLICPATH/
    - /bin/cp $APPPATH/public/.htaccess $PUBLICPATH/ 2>/dev/null || true
    
    # Set correct permissions
    - /bin/chmod -R 755 $APPPATH
    - /bin/chmod -R 775 $APPPATH/storage
    - /bin/chmod -R 775 $APPPATH/bootstrap/cache
    - /bin/chmod -R 755 $PUBLICPATH
