---
deployment:
  tasks:
    # Deploy Laravel directly to public_html
    - export DEPLOYPATH=/home/txepiedg/public_html
    
    # Copy all files to public_html
    - /bin/cp -R . $DEPLOYPATH/
    
    # Set correct permissions
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache
